### ISSUE TITLE
Cannot override default properties from application.yaml with environment variables. 

### ISSUE THREAD

**Issue by AntonAb** [micronaut-projects/micronaut-cassandra#240]
Hi, I need to override cassandra configuration with env.vars (use 2 cluster connections with different configuration). Now it's not possible because it uses StringConvention.RAW (see 
https://github.com/micronaut-projects/micronaut-cassandra/blob/ad634ba7f30604bd36193f6b059ab3b517c77647/cassandra/src/main/java/io/micronaut/cassandra/CassandraSessionFactory.java#L69 ). 

It ignores generated properties. How does it can be resolved?

BR,
Tony

**Comment by wetted** [comment]
@AntonAb can you please provide some examples of env overriding vars you are using? I want to see what you expect to work for overriding application configuration.

**Comment by AntonAb** [comment]
@wetted honestly I don't remember what the cause, it was more than 1 year ago. We don't use Cassandra now.
I've found old configuration:
```
cassandra:
  endpoints: "127.0.0.1:9042"
  unistore:
    advanced:
      metadata:
        schema:
          enabled: false
      auth-provider:
        class: PlainTextAuthProvider
        username: "unistore"
        password: "password here"
    basic:
      session-keyspace: unistore

  unistore2:
    advanced:
      metadata:
        schema:
          enabled: false
      auth-provider:
        class: PlainTextAuthProvider
        username: "unistore2"
        password: "password here"
    basic:
      session-keyspace: gac_universal_storage
```
All credentials config should be defined from env variables. Something like this CASSANDRA_UNISTORE_ADVANCED_AUTH_PROVIDER_USERNAME=REAL_CASSANDRA_USER
